# Common settings for all DBs
common: &COMMON
  encoding: utf8
  pool: 5
  timeout: 5000
  adapter: mysql2
  user: root

production:
  <<: *COMMON
  database: eopas

development:
  <<: *COMMON
  database: eoaps_devel

test: &TEST
  <<: *COMMON
  database: eopas_test
